Report 50054 "ETI. PORTUGES"
{
    UseRequestPage = false;
    RDLCLayout = './Layouts/ETI.PORTUGES.rdlc';
    DefaultLayout = RDLC;

    dataset
    {
        dataitem("Extended Text Header"; "Extended Text Header")
        {
            /////-DataItemTableView = sorting("Table Name","No.","Language Code","Text No.") where("Table Name"=const('Etiquetas')); 
            RequestFilterFields = "Table Name";
            column(ReportForNavId_1; 1) { } // Autogenerated by ForNav - Do not delete
            column(Text6; Text[6])
            {
            }
            column(descrip; descrip)
            {
            }
            column(Text5; Text[5])
            {
            }
            column(Text4; Text[4])
            {
            }
            column(Text3; Text[3])
            {
            }
            column(Text2; Text[2])
            {
            }
            column(Text1; Text[1])
            {
            }
            trigger OnPreDataItem();
            begin
                LastFieldNo := FieldNo("Table Name");
            end;

            trigger OnAfterGetRecord();
            begin
                X := 0;
                RecL.Reset;
                RecL.SetRange(RecL."Table Name", "Extended Text Header"."Table Name");
                RecL.SetRange(RecL."No.", "Extended Text Header"."No.");
                if RecL.FindFirst then
                    repeat
                        X := X + 1;
                        Text[X] := RecL.Text;
                    until (RecL.Next = 0) or (X = 5);
                Text[6] := RecL."No." + '---------' + CODEXPE;
                descrip := '';
                if RecItem.Get("Extended Text Header"."No.") then begin
                    descrip := RecItem.Description;
                    RecTP.Reset;
                    RecTP.SetRange(RecTP."Item No.", "Extended Text Header"."No.");
                    RecTP.SetRange(RecTP."Language Code", 'PTG');
                    if RecTP.FindFirst then begin
                        descrip := RecTP.Description;
                    end;
                end;
            end;

        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
            area(Content)
            {
                group(Options)
                {
                    Caption = 'Options';
                    field(ForNavOpenDesigner; ReportForNavOpenDesigner)
                    {
                        ApplicationArea = Basic;
                        Caption = 'Design';
                        Visible = ReportForNavAllowDesign;
                    }
                }
            }
        }

    }

    trigger OnInitReport()
    begin
    end;

    trigger OnPostReport()
    begin
    end;

    trigger OnPreReport()
    begin
    end;

    var
        LastFieldNo: Integer;
        FooterPrinted: Boolean;
        Text: array[7] of Text[50];
        RecL: Record "Extended Text Line";
        X: Integer;
        CODEXPE: Code[20];
        descrip: Text[60];
        RecTP: Record "Item Translation";
        RecItem: Record Item;

    procedure NEXPE(NEXPE: Code[20])
    begin
        CODEXPE := NEXPE;
    end;

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    var
        ReportForNavOpenDesigner: Boolean;
        ReportForNavAllowDesign: Boolean;

}
