#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
Report 50108 "Cajas AMAZON"
{
    DefaultLayout = RDLC;
    RDLCLayout = './Layouts/Cajas AMAZON.rdlc';

    dataset
    {
        dataitem("Integer";"Integer")
        {
            MaxIteration = 1;
            column(ReportForNavId_1000000000; 1000000000)
            {
            }
            column(Prod;Prod)
            {
            }
            column(Descrip;Descrip)
            {
            }
            column(Q1;Q[1])
            {
            }
            column(F1;F[1])
            {
            }
            column(L1;L[1])
            {
            }
            column(Q2;Q[2])
            {
            }
            column(F2;F[2])
            {
            }
            column(L2;L[2])
            {
            }
            column(Q3;Q[3])
            {
            }
            column(F3;F[3])
            {
            }
            column(L3;L[3])
            {
            }
            column(Q4;Q[4])
            {
            }
            column(F4;F[4])
            {
            }
            column(L4;L[4])
            {
            }
            column(Q5;Q[5])
            {
            }
            column(F5;F[5])
            {
            }
            column(L5;L[5])
            {
            }
            column(Q6;Q[6])
            {
            }
            column(F6;F[6])
            {
            }
            column(L6;L[6])
            {
            }
            column(Q7;Q[7])
            {
            }
            column(F7;F[7])
            {
            }
            column(L7;L[7])
            {
            }
            column(Q8;Q[8])
            {
            }
            column(F8;F[8])
            {
            }
            column(L8;L[8])
            {
            }
            column(Q9;Q[9])
            {
            }
            column(F9;F[9])
            {
            }
            column(L9;L[9])
            {
            }
            column(Q10;Q[10])
            {
            }
            column(F10;F[10])
            {
            }
            column(L10;L[10])
            {
            }
            column(Q11;Q[11])
            {
            }
            column(F11;F[11])
            {
            }
            column(L11;L[11])
            {
            }
            column(Q12;Q[12])
            {
            }
            column(F12;F[12])
            {
            }
            column(L12;L[12])
            {
            }
            column(Q13;Q[13])
            {
            }
            column(F13;F[13])
            {
            }
            column(L13;L[13])
            {
            }
            column(Q14;Q[14])
            {
            }
            column(F14;F[14])
            {
            }
            column(L14;L[14])
            {
            }
            column(Q15;Q[15])
            {
            }
            column(F15;F[15])
            {
            }
            column(L15;L[15])
            {
            }
            column(Q16;Q[16])
            {
            }
            column(F16;F[16])
            {
            }
            column(L16;L[16])
            {
            }
            column(Q17;Q[17])
            {
            }
            column(F17;F[17])
            {
            }
            column(L17;L[17])
            {
            }
            column(Q18;Q[18])
            {
            }
            column(F18;F[18])
            {
            }
            column(L18;L[18])
            {
            }
            column(Q19;Q[19])
            {
            }
            column(F19;F[19])
            {
            }
            column(L19;L[19])
            {
            }
            column(Q20;Q[20])
            {
            }
            column(F20;F[20])
            {
            }
            column(L20;L[20])
            {
            }
            column(Q21;Q[21])
            {
            }
            column(F21;F[21])
            {
            }
            column(L21;L[21])
            {
            }
            column(Q22;Q[22])
            {
            }
            column(F22;F[22])
            {
            }
            column(L22;L[22])
            {
            }
            column(Q23;Q[23])
            {
            }
            column(F23;F[23])
            {
            }
            column(L23;L[23])
            {
            }
            column(Q24;Q[24])
            {
            }
            column(F24;F[24])
            {
            }
            column(L24;L[24])
            {
            }
            column(Q25;Q[25])
            {
            }
            column(F25;F[25])
            {
            }
            column(L25;L[25])
            {
            }
            column(Q26;Q[26])
            {
            }
            column(F26;F[26])
            {
            }
            column(L26;L[26])
            {
            }
            column(Q27;Q[27])
            {
            }
            column(F27;F[27])
            {
            }
            column(L27;L[27])
            {
            }
            column(Q28;Q[28])
            {
            }
            column(F28;F[28])
            {
            }
            column(L28;L[28])
            {
            }
            column(Q29;Q[29])
            {
            }
            column(F29;F[29])
            {
            }
            column(L29;L[29])
            {
            }
            column(Q30;Q[30])
            {
            }
            column(F30;F[30])
            {
            }
            column(L30;L[30])
            {
            }
            column(Q31;Q[31])
            {
            }
            column(F31;F[31])
            {
            }
            column(L31;L[31])
            {
            }
            column(Q32;Q[32])
            {
            }
            column(F32;F[32])
            {
            }
            column(L32;L[32])
            {
            }
            column(Q33;Q[33])
            {
            }
            column(F33;F[33])
            {
            }
            column(L33;L[33])
            {
            }
            column(Q34;Q[34])
            {
            }
            column(F34;F[34])
            {
            }
            column(L34;L[34])
            {
            }
            column(Q35;Q[35])
            {
            }
            column(F35;F[35])
            {
            }
            column(L35;L[35])
            {
            }
            column(Q36;Q[36])
            {
            }
            column(F36;F[36])
            {
            }
            column(L36;L[36])
            {
            }
            column(Q37;Q[37])
            {
            }
            column(F37;F[37])
            {
            }
            column(L37;L[37])
            {
            }
            column(Q38;Q[38])
            {
            }
            column(F38;F[38])
            {
            }
            column(L38;L[38])
            {
            }
            column(Q39;Q[39])
            {
            }
            column(F39;F[39])
            {
            }
            column(L39;L[39])
            {
            }
            column(Q40;Q[40])
            {
            }
            column(F40;F[40])
            {
            }
            column(L40;L[40])
            {
            }
            column(Q41;Q[41])
            {
            }
            column(F41;F[41])
            {
            }
            column(L41;L[41])
            {
            }
            column(Q42;Q[42])
            {
            }
            column(F42;F[42])
            {
            }
            column(L42;L[42])
            {
            }
            column(Q43;Q[43])
            {
            }
            column(F43;F[43])
            {
            }
            column(L43;L[43])
            {
            }
            column(Q44;Q[44])
            {
            }
            column(F44;F[44])
            {
            }
            column(L44;L[44])
            {
            }
            column(Q45;Q[45])
            {
            }
            column(F45;F[45])
            {
            }
            column(L45;L[45])
            {
            }
            column(Q46;Q[46])
            {
            }
            column(F46;F[46])
            {
            }
            column(L46;L[46])
            {
            }
            column(Q47;Q[47])
            {
            }
            column(F47;F[47])
            {
            }
            column(L47;L[47])
            {
            }
            column(Q48;Q[48])
            {
            }
            column(F48;F[48])
            {
            }
            column(L48;L[48])
            {
            }
            column(Q49;Q[49])
            {
            }
            column(F49;F[49])
            {
            }
            column(L49;L[49])
            {
            }
            column(Q50;Q[50])
            {
            }
            column(F50;F[50])
            {
            }
            column(L50;L[50])
            {
            }
            column(Q51;Q[51])
            {
            }
            column(F51;F[51])
            {
            }
            column(L51;L[51])
            {
            }
            column(Q52;Q[52])
            {
            }
            column(F52;F[52])
            {
            }
            column(L52;L[52])
            {
            }
            column(Q53;Q[53])
            {
            }
            column(F53;F[53])
            {
            }
            column(L53;L[53])
            {
            }
            column(Q54;Q[54])
            {
            }
            column(F54;F[54])
            {
            }
            column(L54;L[54])
            {
            }
            column(Q55;Q[55])
            {
            }
            column(F55;F[55])
            {
            }
            column(L55;L[55])
            {
            }
            column(Q56;Q[56])
            {
            }
            column(F56;F[56])
            {
            }
            column(L56;L[56])
            {
            }
            column(Q57;Q[57])
            {
            }
            column(F57;F[57])
            {
            }
            column(L57;L[57])
            {
            }
            column(Q58;Q[58])
            {
            }
            column(F58;F[58])
            {
            }
            column(L58;L[58])
            {
            }
            column(Q59;Q[59])
            {
            }
            column(F59;F[59])
            {
            }
            column(L59;L[59])
            {
            }
            column(Q60;Q[60])
            {
            }
            column(F60;F[60])
            {
            }
            column(L60;L[60])
            {
            }
            column(Q61;Q[61])
            {
            }
            column(F61;F[61])
            {
            }
            column(L61;L[61])
            {
            }
            column(Q62;Q[62])
            {
            }
            column(F62;F[62])
            {
            }
            column(L62;L[62])
            {
            }
            column(Q63;Q[63])
            {
            }
            column(F63;F[63])
            {
            }
            column(L63;L[63])
            {
            }
            column(Q64;Q[64])
            {
            }
            column(F64;F[64])
            {
            }
            column(L64;L[64])
            {
            }
            column(Q65;Q[65])
            {
            }
            column(F65;F[65])
            {
            }
            column(L65;L[65])
            {
            }
            column(Q66;Q[66])
            {
            }
            column(F66;F[66])
            {
            }
            column(L66;L[66])
            {
            }
            column(Q67;Q[67])
            {
            }
            column(F67;F[67])
            {
            }
            column(L67;L[67])
            {
            }
            column(Q68;Q[68])
            {
            }
            column(F68;F[68])
            {
            }
            column(L68;L[68])
            {
            }
            column(Q69;Q[69])
            {
            }
            column(F69;F[69])
            {
            }
            column(L69;L[69])
            {
            }
            column(Q70;Q[70])
            {
            }
            column(F70;F[70])
            {
            }
            column(L70;L[70])
            {
            }
            column(Q71;Q[71])
            {
            }
            column(F71;F[71])
            {
            }
            column(L71;L[71])
            {
            }
            column(Q72;Q[72])
            {
            }
            column(F72;F[72])
            {
            }
            column(L72;L[72])
            {
            }
            column(Q73;Q[73])
            {
            }
            column(F73;F[73])
            {
            }
            column(L73;L[73])
            {
            }
            column(Q74;Q[74])
            {
            }
            column(F74;F[74])
            {
            }
            column(L74;L[74])
            {
            }
            column(Q75;Q[75])
            {
            }
            column(F75;F[75])
            {
            }
            column(L75;L[75])
            {
            }
            column(Q76;Q[76])
            {
            }
            column(F76;F[76])
            {
            }
            column(L76;L[76])
            {
            }
            column(Q77;Q[77])
            {
            }
            column(F77;F[77])
            {
            }
            column(L77;L[77])
            {
            }
            column(Q78;Q[78])
            {
            }
            column(F78;F[78])
            {
            }
            column(L78;L[78])
            {
            }
            column(Q79;Q[79])
            {
            }
            column(F79;F[79])
            {
            }
            column(L79;L[79])
            {
            }
            column(Q80;Q[80])
            {
            }
            column(F80;F[80])
            {
            }
            column(L80;L[80])
            {
            }
            column(Q81;Q[81])
            {
            }
            column(F81;F[81])
            {
            }
            column(L81;L[81])
            {
            }
            column(Q82;Q[82])
            {
            }
            column(F82;F[82])
            {
            }
            column(L82;L[82])
            {
            }
            column(Q83;Q[83])
            {
            }
            column(F83;F[83])
            {
            }
            column(L83;L[83])
            {
            }
            column(Q84;Q[84])
            {
            }
            column(F84;F[84])
            {
            }
            column(L84;L[84])
            {
            }
            column(Q85;Q[85])
            {
            }
            column(F85;F[85])
            {
            }
            column(L85;L[85])
            {
            }
            column(Q86;Q[86])
            {
            }
            column(F86;F[86])
            {
            }
            column(L86;L[86])
            {
            }
            column(Q87;Q[87])
            {
            }
            column(F87;F[87])
            {
            }
            column(L87;L[87])
            {
            }
            column(Q88;Q[88])
            {
            }
            column(F88;F[88])
            {
            }
            column(L88;L[88])
            {
            }
            column(Q89;Q[89])
            {
            }
            column(F89;F[89])
            {
            }
            column(L89;L[89])
            {
            }
            column(Q90;Q[90])
            {
            }
            column(F90;F[90])
            {
            }
            column(L90;L[90])
            {
            }
            column(Q91;Q[91])
            {
            }
            column(F91;F[91])
            {
            }
            column(L91;L[91])
            {
            }
            column(Q92;Q[92])
            {
            }
            column(F92;F[92])
            {
            }
            column(L92;L[92])
            {
            }
            column(Q93;Q[93])
            {
            }
            column(F93;F[93])
            {
            }
            column(L93;L[93])
            {
            }
            column(Q94;Q[94])
            {
            }
            column(F94;F[94])
            {
            }
            column(L94;L[94])
            {
            }
            column(Q95;Q[95])
            {
            }
            column(F95;F[95])
            {
            }
            column(L95;L[95])
            {
            }
            column(Q96;Q[96])
            {
            }
            column(F96;F[96])
            {
            }
            column(L96;L[96])
            {
            }
            column(Q97;Q[97])
            {
            }
            column(F97;F[97])
            {
            }
            column(L97;L[97])
            {
            }
            column(Q98;Q[98])
            {
            }
            column(F98;F[98])
            {
            }
            column(L98;L[98])
            {
            }
            column(Q99;Q[99])
            {
            }
            column(F99;F[99])
            {
            }
            column(L99;L[99])
            {
            }
            column(Q100;Q[100])
            {
            }
            column(F100;F[100])
            {
            }
            column(L100;L[100])
            {
            }
            column(Q101;Q[101])
            {
            }
            column(F101;F[101])
            {
            }
            column(L101;L[101])
            {
            }
            column(Q102;Q[102])
            {
            }
            column(F102;F[102])
            {
            }
            column(L102;L[102])
            {
            }
            column(Q103;Q[103])
            {
            }
            column(F103;F[103])
            {
            }
            column(L103;L[103])
            {
            }
            column(Q104;Q[104])
            {
            }
            column(F104;F[104])
            {
            }
            column(L104;L[104])
            {
            }
            column(Q105;Q[105])
            {
            }
            column(F105;F[105])
            {
            }
            column(L105;L[105])
            {
            }
            column(Q106;Q[106])
            {
            }
            column(F106;F[106])
            {
            }
            column(L106;L[106])
            {
            }
            column(Q107;Q[107])
            {
            }
            column(F107;F[107])
            {
            }
            column(L107;L[107])
            {
            }
            column(Q108;Q[108])
            {
            }
            column(F108;F[108])
            {
            }
            column(L108;L[108])
            {
            }
            column(Q109;Q[109])
            {
            }
            column(F109;F[109])
            {
            }
            column(L109;L[109])
            {
            }
            column(Q110;Q[110])
            {
            }
            column(F110;F[110])
            {
            }
            column(L110;L[110])
            {
            }
            column(Q111;Q[111])
            {
            }
            column(F111;F[111])
            {
            }
            column(L111;L[111])
            {
            }
            column(Q112;Q[112])
            {
            }
            column(F112;F[112])
            {
            }
            column(L112;L[112])
            {
            }
            column(Q113;Q[113])
            {
            }
            column(F113;F[113])
            {
            }
            column(L113;L[113])
            {
            }
            column(Q114;Q[114])
            {
            }
            column(F114;F[114])
            {
            }
            column(L114;L[114])
            {
            }
            column(Q115;Q[115])
            {
            }
            column(F115;F[115])
            {
            }
            column(L115;L[115])
            {
            }
            column(Q116;Q[116])
            {
            }
            column(F116;F[116])
            {
            }
            column(L116;L[116])
            {
            }
            column(Q117;Q[117])
            {
            }
            column(F117;F[117])
            {
            }
            column(L117;L[117])
            {
            }
            column(Q118;Q[118])
            {
            }
            column(F118;F[118])
            {
            }
            column(L118;L[118])
            {
            }
            column(Q119;Q[119])
            {
            }
            column(F119;F[119])
            {
            }
            column(L119;L[119])
            {
            }
            column(Q120;Q[120])
            {
            }
            column(F120;F[120])
            {
            }
            column(L120;L[120])
            {
            }
            column(Q121;Q[121])
            {
            }
            column(F121;F[121])
            {
            }
            column(L121;L[121])
            {
            }
            column(Q122;Q[122])
            {
            }
            column(F122;F[122])
            {
            }
            column(L122;L[122])
            {
            }
            column(Q123;Q[123])
            {
            }
            column(F123;F[123])
            {
            }
            column(L123;L[123])
            {
            }
            column(Q124;Q[124])
            {
            }
            column(F124;F[124])
            {
            }
            column(L124;L[124])
            {
            }
            column(Q125;Q[125])
            {
            }
            column(F125;F[125])
            {
            }
            column(L125;L[125])
            {
            }
            column(Q126;Q[126])
            {
            }
            column(F126;F[126])
            {
            }
            column(L126;L[126])
            {
            }
            column(Q127;Q[127])
            {
            }
            column(F127;F[127])
            {
            }
            column(L127;L[127])
            {
            }
            column(Q128;Q[128])
            {
            }
            column(F128;F[128])
            {
            }
            column(L128;L[128])
            {
            }
            column(Q129;Q[129])
            {
            }
            column(F129;F[129])
            {
            }
            column(L129;L[129])
            {
            }
            column(Q130;Q[130])
            {
            }
            column(F130;F[130])
            {
            }
            column(L130;L[130])
            {
            }
            column(Q131;Q[131])
            {
            }
            column(F131;F[131])
            {
            }
            column(L131;L[131])
            {
            }
            column(Q132;Q[132])
            {
            }
            column(F132;F[132])
            {
            }
            column(L132;L[132])
            {
            }
            column(Q133;Q[133])
            {
            }
            column(F133;F[133])
            {
            }
            column(L133;L[133])
            {
            }
            column(Q134;Q[134])
            {
            }
            column(F134;F[134])
            {
            }
            column(L134;L[134])
            {
            }
            column(Q135;Q[135])
            {
            }
            column(F135;F[135])
            {
            }
            column(L135;L[135])
            {
            }
            column(Q136;Q[136])
            {
            }
            column(F136;F[136])
            {
            }
            column(L136;L[136])
            {
            }
            column(Q137;Q[137])
            {
            }
            column(F137;F[137])
            {
            }
            column(L137;L[137])
            {
            }
            column(Q138;Q[138])
            {
            }
            column(F138;F[138])
            {
            }
            column(L138;L[138])
            {
            }
            column(Q139;Q[139])
            {
            }
            column(F139;F[139])
            {
            }
            column(L139;L[139])
            {
            }
            column(Q140;Q[140])
            {
            }
            column(F140;F[140])
            {
            }
            column(L140;L[140])
            {
            }
            column(Q141;Q[141])
            {
            }
            column(F141;F[141])
            {
            }
            column(L141;L[141])
            {
            }
            column(Q142;Q[142])
            {
            }
            column(F142;F[142])
            {
            }
            column(L142;L[142])
            {
            }
            column(Q143;Q[143])
            {
            }
            column(F143;F[143])
            {
            }
            column(L143;L[143])
            {
            }
            column(Q144;Q[144])
            {
            }
            column(F144;F[144])
            {
            }
            column(L144;L[144])
            {
            }
            column(Q145;Q[145])
            {
            }
            column(F145;F[145])
            {
            }
            column(L145;L[145])
            {
            }
            column(Q146;Q[146])
            {
            }
            column(F146;F[146])
            {
            }
            column(L146;L[146])
            {
            }
            column(Q147;Q[147])
            {
            }
            column(F147;F[147])
            {
            }
            column(L147;L[147])
            {
            }
            column(Q148;Q[148])
            {
            }
            column(F148;F[148])
            {
            }
            column(L148;L[148])
            {
            }
            column(Q149;Q[149])
            {
            }
            column(F149;F[149])
            {
            }
            column(L149;L[149])
            {
            }
            column(Q150;Q[150])
            {
            }
            column(F150;F[150])
            {
            }
            column(L150;L[150])
            {
            }
            column(Q151;Q[151])
            {
            }
            column(F151;F[151])
            {
            }
            column(L151;L[151])
            {
            }
            column(Q152;Q[152])
            {
            }
            column(F152;F[152])
            {
            }
            column(L152;L[152])
            {
            }
            column(Q153;Q[153])
            {
            }
            column(F153;F[153])
            {
            }
            column(L153;L[153])
            {
            }
            column(Q154;Q[154])
            {
            }
            column(F154;F[154])
            {
            }
            column(L154;L[154])
            {
            }
            column(Q155;Q[155])
            {
            }
            column(F155;F[155])
            {
            }
            column(L155;L[155])
            {
            }
            column(Q156;Q[156])
            {
            }
            column(F156;F[156])
            {
            }
            column(L156;L[156])
            {
            }
            column(Q157;Q[157])
            {
            }
            column(F157;F[157])
            {
            }
            column(L157;L[157])
            {
            }
            column(Q158;Q[158])
            {
            }
            column(F158;F[158])
            {
            }
            column(L158;L[158])
            {
            }
            column(Q159;Q[159])
            {
            }
            column(F159;F[159])
            {
            }
            column(L159;L[159])
            {
            }
            column(Q160;Q[160])
            {
            }
            column(F160;F[160])
            {
            }
            column(L160;L[160])
            {
            }
            column(Q161;Q[161])
            {
            }
            column(F161;F[161])
            {
            }
            column(L161;L[161])
            {
            }
            column(Q162;Q[162])
            {
            }
            column(F162;F[162])
            {
            }
            column(L162;L[162])
            {
            }
            column(Q163;Q[163])
            {
            }
            column(F163;F[163])
            {
            }
            column(L163;L[163])
            {
            }
            column(Q164;Q[164])
            {
            }
            column(F164;F[164])
            {
            }
            column(L164;L[164])
            {
            }
            column(Q165;Q[165])
            {
            }
            column(F165;F[165])
            {
            }
            column(L165;L[165])
            {
            }
            column(Q166;Q[166])
            {
            }
            column(F166;F[166])
            {
            }
            column(L166;L[166])
            {
            }
            column(Q167;Q[167])
            {
            }
            column(F167;F[167])
            {
            }
            column(L167;L[167])
            {
            }
            column(Q168;Q[168])
            {
            }
            column(F168;F[168])
            {
            }
            column(L168;L[168])
            {
            }
            column(Q169;Q[169])
            {
            }
            column(F169;F[169])
            {
            }
            column(L169;L[169])
            {
            }
            column(Q170;Q[170])
            {
            }
            column(F170;F[170])
            {
            }
            column(L170;L[170])
            {
            }
            column(Q171;Q[171])
            {
            }
            column(F171;F[171])
            {
            }
            column(L171;L[171])
            {
            }
            column(Q172;Q[172])
            {
            }
            column(F172;F[172])
            {
            }
            column(L172;L[172])
            {
            }
            column(Q173;Q[173])
            {
            }
            column(F173;F[173])
            {
            }
            column(L173;L[173])
            {
            }
            column(Q174;Q[174])
            {
            }
            column(F174;F[174])
            {
            }
            column(L174;L[174])
            {
            }
            column(Q175;Q[175])
            {
            }
            column(F175;F[175])
            {
            }
            column(L175;L[175])
            {
            }
            column(Q176;Q[176])
            {
            }
            column(F176;F[176])
            {
            }
            column(L176;L[176])
            {
            }
            column(Q177;Q[177])
            {
            }
            column(F177;F[177])
            {
            }
            column(L177;L[177])
            {
            }
            column(Q178;Q[178])
            {
            }
            column(F178;F[178])
            {
            }
            column(L178;L[178])
            {
            }
            column(Q179;Q[179])
            {
            }
            column(F179;F[179])
            {
            }
            column(L179;L[179])
            {
            }
            column(Q180;Q[180])
            {
            }
            column(F180;F[180])
            {
            }
            column(L180;L[180])
            {
            }
            column(Q181;Q[181])
            {
            }
            column(F181;F[181])
            {
            }
            column(L181;L[181])
            {
            }
            column(Q182;Q[182])
            {
            }
            column(F182;F[182])
            {
            }
            column(L182;L[182])
            {
            }
            column(Q183;Q[183])
            {
            }
            column(F183;F[183])
            {
            }
            column(L183;L[183])
            {
            }
            column(Q184;Q[184])
            {
            }
            column(F184;F[184])
            {
            }
            column(L184;L[184])
            {
            }
            column(Q185;Q[185])
            {
            }
            column(F185;F[185])
            {
            }
            column(L185;L[185])
            {
            }
            column(Q186;Q[186])
            {
            }
            column(F186;F[186])
            {
            }
            column(L186;L[186])
            {
            }
            column(Q187;Q[187])
            {
            }
            column(F187;F[187])
            {
            }
            column(L187;L[187])
            {
            }
            column(Q188;Q[188])
            {
            }
            column(F188;F[188])
            {
            }
            column(L188;L[188])
            {
            }
            column(Q189;Q[189])
            {
            }
            column(F189;F[189])
            {
            }
            column(L189;L[189])
            {
            }
            column(Q190;Q[190])
            {
            }
            column(F190;F[190])
            {
            }
            column(L190;L[190])
            {
            }
            column(Q191;Q[191])
            {
            }
            column(F191;F[191])
            {
            }
            column(L191;L[191])
            {
            }
            column(Q192;Q[192])
            {
            }
            column(F192;F[192])
            {
            }
            column(L192;L[192])
            {
            }
            column(Q193;Q[193])
            {
            }
            column(F193;F[193])
            {
            }
            column(L193;L[193])
            {
            }
            column(Q194;Q[194])
            {
            }
            column(F194;F[194])
            {
            }
            column(L194;L[194])
            {
            }
            column(Q195;Q[195])
            {
            }
            column(F195;F[195])
            {
            }
            column(L195;L[195])
            {
            }
            column(Q196;Q[196])
            {
            }
            column(F196;F[196])
            {
            }
            column(L196;L[196])
            {
            }
            column(Q197;Q[197])
            {
            }
            column(F197;F[197])
            {
            }
            column(L197;L[197])
            {
            }
            column(Q198;Q[198])
            {
            }
            column(F198;F[198])
            {
            }
            column(L198;L[198])
            {
            }
            column(Q199;Q[199])
            {
            }
            column(F199;F[199])
            {
            }
            column(L199;L[199])
            {
            }
            column(Q200;Q[200])
            {
            }
            column(F200;F[200])
            {
            }
            column(L200;L[200])
            {
            }
            column(Q201;Q[201])
            {
            }
            column(F201;F[201])
            {
            }
            column(L201;L[201])
            {
            }
            column(Q202;Q[202])
            {
            }
            column(F202;F[202])
            {
            }
            column(L202;L[202])
            {
            }
            column(Q203;Q[203])
            {
            }
            column(F203;F[203])
            {
            }
            column(L203;L[203])
            {
            }
            column(Q204;Q[204])
            {
            }
            column(F204;F[204])
            {
            }
            column(L204;L[204])
            {
            }
            column(Q205;Q[205])
            {
            }
            column(F205;F[205])
            {
            }
            column(L205;L[205])
            {
            }
            column(Q206;Q[206])
            {
            }
            column(F206;F[206])
            {
            }
            column(L206;L[206])
            {
            }
            column(Q207;Q[207])
            {
            }
            column(F207;F[207])
            {
            }
            column(L207;L[207])
            {
            }
            column(Q208;Q[208])
            {
            }
            column(F208;F[208])
            {
            }
            column(L208;L[208])
            {
            }
            column(Q209;Q[209])
            {
            }
            column(F209;F[209])
            {
            }
            column(L209;L[209])
            {
            }
            column(Q210;Q[210])
            {
            }
            column(F210;F[210])
            {
            }
            column(L210;L[210])
            {
            }
            column(Q211;Q[211])
            {
            }
            column(F211;F[211])
            {
            }
            column(L211;L[211])
            {
            }
            column(Q212;Q[212])
            {
            }
            column(F212;F[212])
            {
            }
            column(L212;L[212])
            {
            }
            column(Q213;Q[213])
            {
            }
            column(F213;F[213])
            {
            }
            column(L213;L[213])
            {
            }
            column(Q214;Q[214])
            {
            }
            column(F214;F[214])
            {
            }
            column(L214;L[214])
            {
            }
            column(Q215;Q[215])
            {
            }
            column(F215;F[215])
            {
            }
            column(L215;L[215])
            {
            }
            column(Q216;Q[216])
            {
            }
            column(F216;F[216])
            {
            }
            column(L216;L[216])
            {
            }
            column(Q217;Q[217])
            {
            }
            column(F217;F[217])
            {
            }
            column(L217;L[217])
            {
            }
            column(Q218;Q[218])
            {
            }
            column(F218;F[218])
            {
            }
            column(L218;L[218])
            {
            }
            column(Q219;Q[219])
            {
            }
            column(F219;F[219])
            {
            }
            column(L219;L[219])
            {
            }
            column(Q220;Q[220])
            {
            }
            column(F220;F[220])
            {
            }
            column(L220;L[220])
            {
            }
            column(Q221;Q[221])
            {
            }
            column(F221;F[221])
            {
            }
            column(L221;L[221])
            {
            }
            column(Q222;Q[222])
            {
            }
            column(F222;F[222])
            {
            }
            column(L222;L[222])
            {
            }
            column(Q223;Q[223])
            {
            }
            column(F223;F[223])
            {
            }
            column(L223;L[223])
            {
            }
            column(Q224;Q[224])
            {
            }
            column(F224;F[224])
            {
            }
            column(L224;L[224])
            {
            }
            column(Q225;Q[225])
            {
            }
            column(F225;F[225])
            {
            }
            column(L225;L[225])
            {
            }
            column(Q226;Q[226])
            {
            }
            column(F226;F[226])
            {
            }
            column(L226;L[226])
            {
            }
            column(Q227;Q[227])
            {
            }
            column(F227;F[227])
            {
            }
            column(L227;L[227])
            {
            }
            column(Q228;Q[228])
            {
            }
            column(F228;F[228])
            {
            }
            column(L228;L[228])
            {
            }
            column(Q229;Q[229])
            {
            }
            column(F229;F[229])
            {
            }
            column(L229;L[229])
            {
            }
            column(Q230;Q[230])
            {
            }
            column(F230;F[230])
            {
            }
            column(L230;L[230])
            {
            }
            column(Q231;Q[231])
            {
            }
            column(F231;F[231])
            {
            }
            column(L231;L[231])
            {
            }
            column(Q232;Q[232])
            {
            }
            column(F232;F[232])
            {
            }
            column(L232;L[232])
            {
            }
            column(Q233;Q[233])
            {
            }
            column(F233;F[233])
            {
            }
            column(L233;L[233])
            {
            }
            column(Q234;Q[234])
            {
            }
            column(F234;F[234])
            {
            }
            column(L234;L[234])
            {
            }
            column(Q235;Q[235])
            {
            }
            column(F235;F[235])
            {
            }
            column(L235;L[235])
            {
            }
            column(Q236;Q[236])
            {
            }
            column(F236;F[236])
            {
            }
            column(L236;L[236])
            {
            }
            column(Q237;Q[237])
            {
            }
            column(F237;F[237])
            {
            }
            column(L237;L[237])
            {
            }
            column(Q238;Q[238])
            {
            }
            column(F238;F[238])
            {
            }
            column(L238;L[238])
            {
            }
            column(Q239;Q[239])
            {
            }
            column(F239;F[239])
            {
            }
            column(L239;L[239])
            {
            }
            column(Q240;Q[240])
            {
            }
            column(F240;F[240])
            {
            }
            column(L240;L[240])
            {
            }
            column(Q241;Q[241])
            {
            }
            column(F241;F[241])
            {
            }
            column(L241;L[241])
            {
            }
            column(Q242;Q[242])
            {
            }
            column(F242;F[242])
            {
            }
            column(L242;L[242])
            {
            }
            column(Q243;Q[243])
            {
            }
            column(F243;F[243])
            {
            }
            column(L243;L[243])
            {
            }
            column(Q244;Q[244])
            {
            }
            column(F244;F[244])
            {
            }
            column(L244;L[244])
            {
            }
            column(Q245;Q[245])
            {
            }
            column(F245;F[245])
            {
            }
            column(L245;L[245])
            {
            }
            column(Q246;Q[246])
            {
            }
            column(F246;F[246])
            {
            }
            column(L246;L[246])
            {
            }
            column(Q247;Q[247])
            {
            }
            column(F247;F[247])
            {
            }
            column(L247;L[247])
            {
            }
            column(Q248;Q[248])
            {
            }
            column(F248;F[248])
            {
            }
            column(L248;L[248])
            {
            }
            column(Q249;Q[249])
            {
            }
            column(F249;F[249])
            {
            }
            column(L249;L[249])
            {
            }
            column(Q250;Q[250])
            {
            }
            column(F250;F[250])
            {
            }
            column(L250;L[250])
            {
            }
            column(Q251;Q[251])
            {
            }
            column(F251;F[251])
            {
            }
            column(L251;L[251])
            {
            }
            column(Q252;Q[252])
            {
            }
            column(F252;F[252])
            {
            }
            column(L252;L[252])
            {
            }
            column(Q253;Q[253])
            {
            }
            column(F253;F[253])
            {
            }
            column(L253;L[253])
            {
            }
            column(Q254;Q[254])
            {
            }
            column(F254;F[254])
            {
            }
            column(L254;L[254])
            {
            }
            column(Q255;Q[255])
            {
            }
            column(F255;F[255])
            {
            }
            column(L255;L[255])
            {
            }
            column(Q256;Q[256])
            {
            }
            column(F256;F[256])
            {
            }
            column(L256;L[256])
            {
            }
            column(Q257;Q[257])
            {
            }
            column(F257;F[257])
            {
            }
            column(L257;L[257])
            {
            }
            column(Q258;Q[258])
            {
            }
            column(F258;F[258])
            {
            }
            column(L258;L[258])
            {
            }
            column(Q259;Q[259])
            {
            }
            column(F259;F[259])
            {
            }
            column(L259;L[259])
            {
            }
            column(Q260;Q[260])
            {
            }
            column(F260;F[260])
            {
            }
            column(L260;L[260])
            {
            }
            column(Q261;Q[261])
            {
            }
            column(F261;F[261])
            {
            }
            column(L261;L[261])
            {
            }
            column(Q262;Q[262])
            {
            }
            column(F262;F[262])
            {
            }
            column(L262;L[262])
            {
            }
            column(Q263;Q[263])
            {
            }
            column(F263;F[263])
            {
            }
            column(L263;L[263])
            {
            }
            column(Q264;Q[264])
            {
            }
            column(F264;F[264])
            {
            }
            column(L264;L[264])
            {
            }
            column(Q265;Q[265])
            {
            }
            column(F265;F[265])
            {
            }
            column(L265;L[265])
            {
            }
            column(Q266;Q[266])
            {
            }
            column(F266;F[266])
            {
            }
            column(L266;L[266])
            {
            }
            column(Q267;Q[267])
            {
            }
            column(F267;F[267])
            {
            }
            column(L267;L[267])
            {
            }
            column(Q268;Q[268])
            {
            }
            column(F268;F[268])
            {
            }
            column(L268;L[268])
            {
            }
            column(Q269;Q[269])
            {
            }
            column(F269;F[269])
            {
            }
            column(L269;L[269])
            {
            }
            column(Q270;Q[270])
            {
            }
            column(F270;F[270])
            {
            }
            column(L270;L[270])
            {
            }
            column(Q271;Q[271])
            {
            }
            column(F271;F[271])
            {
            }
            column(L271;L[271])
            {
            }
            column(Q272;Q[272])
            {
            }
            column(F272;F[272])
            {
            }
            column(L272;L[272])
            {
            }
            column(Q273;Q[273])
            {
            }
            column(F273;F[273])
            {
            }
            column(L273;L[273])
            {
            }
            column(Q274;Q[274])
            {
            }
            column(F274;F[274])
            {
            }
            column(L274;L[274])
            {
            }
            column(Q275;Q[275])
            {
            }
            column(F275;F[275])
            {
            }
            column(L275;L[275])
            {
            }
            column(Q276;Q[276])
            {
            }
            column(F276;F[276])
            {
            }
            column(L276;L[276])
            {
            }
            column(Q277;Q[277])
            {
            }
            column(F277;F[277])
            {
            }
            column(L277;L[277])
            {
            }
            column(Q278;Q[278])
            {
            }
            column(F278;F[278])
            {
            }
            column(L278;L[278])
            {
            }
            column(Q279;Q[279])
            {
            }
            column(F279;F[279])
            {
            }
            column(L279;L[279])
            {
            }
            column(Q280;Q[280])
            {
            }
            column(F280;F[280])
            {
            }
            column(L280;L[280])
            {
            }
            column(Q281;Q[281])
            {
            }
            column(F281;F[281])
            {
            }
            column(L281;L[281])
            {
            }
            column(Q282;Q[282])
            {
            }
            column(F282;F[282])
            {
            }
            column(L282;L[282])
            {
            }
            column(Q283;Q[283])
            {
            }
            column(F283;F[283])
            {
            }
            column(L283;L[283])
            {
            }
            column(Q284;Q[284])
            {
            }
            column(F284;F[284])
            {
            }
            column(L284;L[284])
            {
            }
            column(Q285;Q[285])
            {
            }
            column(F285;F[285])
            {
            }
            column(L285;L[285])
            {
            }
            column(Q286;Q[286])
            {
            }
            column(F286;F[286])
            {
            }
            column(L286;L[286])
            {
            }
            column(Q287;Q[287])
            {
            }
            column(F287;F[287])
            {
            }
            column(L287;L[287])
            {
            }
            column(Q288;Q[288])
            {
            }
            column(F288;F[288])
            {
            }
            column(L288;L[288])
            {
            }
            column(Q289;Q[289])
            {
            }
            column(F289;F[289])
            {
            }
            column(L289;L[289])
            {
            }
            column(Q290;Q[290])
            {
            }
            column(F290;F[290])
            {
            }
            column(L290;L[290])
            {
            }
            column(Q291;Q[291])
            {
            }
            column(F291;F[291])
            {
            }
            column(L291;L[291])
            {
            }
            column(Q292;Q[292])
            {
            }
            column(F292;F[292])
            {
            }
            column(L292;L[292])
            {
            }
            column(Q293;Q[293])
            {
            }
            column(F293;F[293])
            {
            }
            column(L293;L[293])
            {
            }
            column(Q294;Q[294])
            {
            }
            column(F294;F[294])
            {
            }
            column(L294;L[294])
            {
            }
            column(Q295;Q[295])
            {
            }
            column(F295;F[295])
            {
            }
            column(L295;L[295])
            {
            }
            column(Q296;Q[296])
            {
            }
            column(F296;F[296])
            {
            }
            column(L296;L[296])
            {
            }
            column(Q297;Q[297])
            {
            }
            column(F297;F[297])
            {
            }
            column(L297;L[297])
            {
            }
            column(Q298;Q[298])
            {
            }
            column(F298;F[298])
            {
            }
            column(L298;L[298])
            {
            }
            column(Q299;Q[299])
            {
            }
            column(F299;F[299])
            {
            }
            column(L299;L[299])
            {
            }
            column(Q300;Q[300])
            {
            }
            column(F300;F[300])
            {
            }
            column(L300;L[300])
            {
            }

            trigger OnAfterGetRecord()
            begin

                SalesShipmentHeader.Reset;
                SalesShipmentHeader.SetRange("Nº expedición",Nexpe);
                if SalesShipmentHeader.FindFirst then repeat
                    SalesShipmentLine.Reset;
                    SalesShipmentLine.SetRange(SalesShipmentLine."Document No.",SalesShipmentHeader."No.");
                    if SalesShipmentLine.FindFirst then repeat
                         if SalesShipmentLine.Type=SalesShipmentLine.Type::Item then begin

                            Q_Inners:=0;
                            Q_Masters:=0;
                            Q_Unidades:=0;
                            Resto_inner:=0;
                            Resto_uni:=0;
                            SalesShipmentLine.CalcFields("Cantidad inner","Cantidad master");
                            if SalesShipmentLine."Cantidad master"<>0 then begin
                                Q_Masters:=ROUND(SalesShipmentLine.Quantity/SalesShipmentLine."Cantidad master",1,'<');
                                if Q_Masters*SalesShipmentLine."Cantidad master"<>SalesShipmentLine.Quantity then begin
                                    Resto_inner:=SalesShipmentLine.Quantity-(Q_Masters*SalesShipmentLine."Cantidad master");
                                end;
                            end;
                            if (Resto_inner>=SalesShipmentLine."Cantidad inner") and (SalesShipmentLine."Cantidad inner"<>1) then begin
                                if Resto_inner<>0 then begin
                                    if SalesShipmentLine."Cantidad inner"<>0 then begin
                                        Q_Inners:=ROUND(Resto_inner/SalesShipmentLine."Cantidad inner",1,'<');
                                        if (Q_Masters*SalesShipmentLine."Cantidad master")+
                                            (Q_Inners*SalesShipmentLine."Cantidad inner")<>SalesShipmentLine.Quantity then begin
                                            Resto_uni:=SalesShipmentLine.Quantity-((Q_Masters*SalesShipmentLine."Cantidad master")+
                                                   (Q_Inners*SalesShipmentLine."Cantidad inner"));
                                        end;
                                    end;
                                end;
                            end;
                            if (Resto_inner<SalesShipmentLine."Cantidad inner") then begin
                                Resto_uni:=Resto_inner;
                            end;
                            if (SalesShipmentLine."Cantidad inner"=1) then begin
                                Resto_uni:=Resto_inner;
                            end;
                            if Resto_uni<>0 then begin
                                Q_Unidades:=Resto_uni;
                            end;
                            NCAJAS:=Q_Inners+Q_Masters;
                            if NCAJAS<>0 then begin
                                CONTA:=0;
                                repeat
                                    CONTA:=CONTA+1;
                                    X:=X+1;
                                    Q[X]:=SalesShipmentLine."Cantidad master";
                                until NCAJAS=CONTA;
                            end;
                        end;
                    until SalesShipmentLine.Next=0;
                until SalesShipmentHeader.Next=0;
            end;
        }
    }

    requestpage
    {

        layout
        {
            area(content)
            {
                field(Nexpe;Nexpe)
                {
                    ApplicationArea = Basic;
                }
            }
        }

        actions
        {
        }
    }

    labels
    {
    }

    var
        Prod: Code[20];
        Descrip: Text;
        Q: array [300] of Integer;
        F: array [300] of Integer;
        L: array [300] of Integer;
        Nexpe: Code[20];
        SalesShipmentHeader: Record "Sales Shipment Header";
        SalesShipmentLine: Record "Sales Shipment Line";
        Q_Inners: Integer;
        Q_Masters: Integer;
        Q_Unidades: Integer;
        Resto_inner: Integer;
        Resto_uni: Integer;
        X: Integer;
        NCAJAS: Integer;
        CONTA: Integer;
}

